import { BotModule } from "../types/generator.types";

interface BuildOptions {
  botName: string;
  prefix: string;
  generatorVersion: string;
  templateUsed: string;
}

export class FileBuilder {
  static buildFiles(modules: BotModule[], options: BuildOptions) {
    const files: { path: string; content: string }[] = [];
    const commands: string[] = [];
    const events: string[] = [];
    const requiredPackages: Record<string, string> = {
      "discord.js": "^14.14.1",
      dotenv: "^16.3.1",
    };
    const envVars: Record<string, string> = {
      DISCORD_TOKEN: "YOUR_BOT_TOKEN_HERE",
      CLIENT_ID: "YOUR_CLIENT_ID_HERE",
    };
    const moduleIds = modules.map((m) => m.metadata.id);

    // Collect module specific contents
    for (const mod of modules) {
      if (mod.commands) {
        for (const cmd of mod.commands) {
          files.push({ path: `src/${cmd.path}`, content: cmd.content });
          commands.push(cmd.path);
        }
      }
      if (mod.events) {
        for (const evt of mod.events) {
          files.push({ path: `src/${evt.path}`, content: evt.content });
          events.push(evt.path);
        }
      }
      if (mod.metadata.requiredPackages) {
        Object.assign(requiredPackages, mod.metadata.requiredPackages);
      }
      if (mod.env) {
        Object.assign(envVars, mod.env);
      }
    }

    // README
    files.push({
      path: "README.md",
      content: `# ${options.botName}\n\nGenerated by Botrixa Generator (v${options.generatorVersion})\n\n## Quick Start\n\n1. Install dependencies:\n   \`\`\`bash\n   npm install\n   \`\`\`\n2. Configure environment:\n   \`\`\`bash\n   cp .env.example .env\n   \`\`\`\n   Edit \`.env\` and add your token.\n3. Build the bot:\n   \`\`\`bash\n   npm run build\n   \`\`\`\n4. Start the bot:\n   \`\`\`bash\n   npm start\n   \`\`\`\n`,
    });

    // Package.json
    files.push({
      path: "package.json",
      content: JSON.stringify(
        {
          name: options.botName.toLowerCase().replace(/\s+/g, "-"),
          version: "1.0.0",
          main: "dist/index.js",
          scripts: {
            build: "tsc",
            start: "node dist/index.js",
            dev: "ts-node src/index.ts",
          },
          dependencies: requiredPackages,
          devDependencies: {
            typescript: "^5.3.3",
            "@types/node": "^20.11.0",
            "ts-node": "^10.9.2",
          },
        },
        null,
        2
      ),
    });

    // Config
    const configLines = Object.keys(envVars)
      .filter((k) => k !== "DISCORD_TOKEN" && k !== "CLIENT_ID")
      .map((k) => `  ${k}: process.env.${k}`)
      .join(",\n");
    files.push({
      path: "src/config/index.ts",
      content: `import dotenv from "dotenv";\ndotenv.config();\n\nexport const config = {\n  DISCORD_TOKEN: process.env.DISCORD_TOKEN,\n  CLIENT_ID: process.env.CLIENT_ID,\n  PREFIX: "${options.prefix}",\n${configLines}\n};\n`,
    });

    // .env.example
    files.push({
      path: ".env.example",
      content: Object.entries(envVars)
        .map(([k, v]) => `${k}=${v}`)
        .join("\n"),
    });

    // Manifest
    files.push({
      path: "botrixa.manifest.json",
      content: JSON.stringify(
        {
          generatorVersion: options.generatorVersion,
          template: options.templateUsed,
          modules: moduleIds,
        },
        null,
        2
      ),
    });

    // tsconfig.json
    files.push({
      path: "tsconfig.json",
      content: JSON.stringify(
        {
          compilerOptions: {
            target: "es2022",
            module: "commonjs",
            rootDir: "./src",
            outDir: "./dist",
            strict: true,
            esModuleInterop: true,
            skipLibCheck: true,
            forceConsistentCasingInFileNames: true,
          },
          include: ["src/**/*"],
        },
        null,
        2
      ),
    });

    // Entrypoint and basic handlers for the MVP
    files.push({
      path: "src/index.ts",
      content: `import { Client, GatewayIntentBits, Collection } from "discord.js";\nimport { config } from "./config";\nimport fs from "fs";\nimport path from "path";\n\nconst client = new Client({\n  intents: [\n    GatewayIntentBits.Guilds,\n    GatewayIntentBits.GuildMessages,\n    GatewayIntentBits.MessageContent,\n    GatewayIntentBits.GuildMembers\n  ]\n});\n\n// @ts-ignore\nclient.commands = new Collection();\n\nasync function loadCommands() {\n  const foldersPath = path.join(__dirname, 'commands');\n  if (!fs.existsSync(foldersPath)) return;\n  const commandFolders = fs.readdirSync(foldersPath);\n  for (const folder of commandFolders) {\n    const commandsPath = path.join(foldersPath, folder);\n    const commandFiles = fs.readdirSync(commandsPath).filter((file: string) => file.endsWith('.js') || file.endsWith('.ts'));\n    for (const file of commandFiles) {\n      const filePath = path.join(commandsPath, file);\n      const command = require(filePath).default;\n      if ('data' in command && 'execute' in command) {\n        // @ts-ignore\n        client.commands.set(command.data.name, command);\n      }\n    }\n  }\n}\n\nasync function loadEvents() {\n  const eventsPath = path.join(__dirname, 'events');\n  if (!fs.existsSync(eventsPath)) return;\n  const eventFiles = fs.readdirSync(eventsPath).filter((file: string) => file.endsWith('.js') || file.endsWith('.ts'));\n  for (const file of eventFiles) {\n    const filePath = path.join(eventsPath, file);\n    const event = require(filePath).default;\n    if (event.once) {\n      client.once(event.name, (...args) => event.execute(...args));\n    } else {\n      client.on(event.name, (...args) => event.execute(...args));\n    }\n  }\n}\n\nclient.once('ready', () => {\n  console.log(\`Logged in as \${client.user?.tag}!\`);\n});\n\nclient.on('interactionCreate', async interaction => {\n  if (!interaction.isChatInputCommand()) return;\n  // @ts-ignore\n  const command = client.commands.get(interaction.commandName);\n  if (!command) return;\n  try {\n    await command.execute(interaction);\n  } catch (error) {\n    console.error(error);\n    if (interaction.replied || interaction.deferred) {\n      await interaction.followUp({ content: 'There was an error while executing this command!', ephemeral: true });\n    } else {\n      await interaction.reply({ content: 'There was an error while executing this command!', ephemeral: true });\n    }\n  }\n});\n\n(async () => {\n  await loadCommands();\n  await loadEvents();\n  await client.login(config.DISCORD_TOKEN);\n})();\n`,
    });

    return files;
  }
}
